### ISSUE TITLE
removed from CRAN

### ISSUE THREAD

**Issue by nicorost** [Appsilon/semantic.dashboard#170]
Hi,

it seems like the package was removed from CRAN: https://cran.r-project.org/web/packages/semantic.dashboard/index.html

Do you know why or if it will be available again anytime soon?

Thank you and best regards!

**Comment by osenan** [comment]
Hi,

Package was removed from CRAN due to its dependence on shiny.semantic package, which was also removed for some days during last week. Now shiny.semantic is back on CRAN https://cran.r-project.org/web/packages/shiny.semantic/index.html so you can expect that in a short time semantic.dashboard will be back as well.

Sorry for the inconveniences,
Oriol
